# Generated by Django 3.0.7 on 2020-07-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0007_auto_20200711_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[('frontend', 'Фронтенд'),
                                            ('backend', 'Бэкенд'),
                                            ('gamedev', 'Геймдев'),
                                            ('devops', 'Девопс'),
                                            ('design', 'Дизайн'),
                                            ('products', 'Продукты'),
                                            ('management', 'Менеджмент'),
                                            ('testing', 'Тестирование')],
                                   default='intern', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='specialty',
            field=models.CharField(
                choices=[('frontend', 'Фронтенд'), ('backend', 'Бэкенд'), ('gamedev', 'Геймдев'), ('devops', 'Девопс'),
                         ('design', 'Дизайн'), ('products', 'Продукты'), ('management', 'Менеджмент'),
                         ('testing', 'Тестирование')], default='backend', max_length=20),
            preserve_default=False,
        ),
    ]
