# Generated by Django 3.0.7 on 2020-07-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0008_auto_20200711_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(
                choices=[('intern', 'intern'), ('junior', 'junior'), ('middle', 'middle'), ('senior', 'senior'),
                         ('lead', 'lead')], max_length=15),
        ),
    ]
